import { createSlice } from "@reduxjs/toolkit";
export const StudentSlice = createSlice({
    name: "student",

    initialState: {
        students: [{
            id: 1,
            studentId: "STU001",
            photo: "https://randomuser.me/api/portraits/women/1.jpg",
            firstName: "Samantha",
            lastName: "William",
            grade: "VII A",
            dateOfBirth: "2008-05-12",
            placeOfBirth: "Jakarta",
            email: "samantha.william@mail.com",
            phone: "+628111111111",
            parentName: "Maria William",
            address: "Jakarta, Indonesia",
            parentFirstName: "Maria",
            parentLastName: "William",
            parentEmail: "maria.william@mail.com",
            parentPhone: "+628100000001",
            parentAddress: "Jakarta, Indonesia",
            payment: "cash",
        },
        {
            id: 2,
            studentId: "STU002",
            photo: "https://randomuser.me/api/portraits/men/2.jpg",
            firstName: "Tony",
            lastName: "Soap",
            grade: "VII B",
            dateOfBirth: "2008-07-18",
            placeOfBirth: "Bandung",
            email: "tony.soap@mail.com",
            phone: "+628111111112",
            parentName: "Robert Soap",
            address: "Bandung, Indonesia",
            parentFirstName: "Robert",
            parentLastName: "Soap",
            parentEmail: "robert.soap@mail.com",
            parentPhone: "+628100000002",
            parentAddress: "Bandung, Indonesia",
            payment: "debit",
        },
        {
            id: 3,
            studentId: "STU003",
            photo: "https://randomuser.me/api/portraits/women/3.jpg",
            firstName: "Karen",
            lastName: "Hope",
            grade: "VII C",
            dateOfBirth: "2009-01-25",
            placeOfBirth: "Surabaya",
            email: "karen.hope@mail.com",
            phone: "+628111111113",
            parentName: "Linda Hope",
            address: "Surabaya, Indonesia",
            parentFirstName: "Linda",
            parentLastName: "Hope",
            parentEmail: "linda.hope@mail.com",
            parentPhone: "+628100000003",
            parentAddress: "Surabaya, Indonesia",
            payment: "cash",
        },
        {
            id: 4,
            studentId: "STU004",
            photo: "https://randomuser.me/api/portraits/men/4.jpg",
            firstName: "Jordan",
            lastName: "Nico",
            grade: "VIII A",
            dateOfBirth: "2007-09-30",
            placeOfBirth: "Yogyakarta",
            email: "jordan.nico@mail.com",
            phone: "+628111111114",
            parentName: "Michael Nico",
            address: "Yogyakarta, Indonesia",
            parentFirstName: "Michael",
            parentLastName: "Nico",
            parentEmail: "michael.nico@mail.com",
            parentPhone: "+628100000004",
            parentAddress: "Yogyakarta, Indonesia",
            payment: "debit",
        },
        {
            id: 5,
            studentId: "STU005",
            photo: "https://randomuser.me/api/portraits/women/5.jpg",
            firstName: "Nadila",
            lastName: "Adja",
            grade: "VIII B",
            dateOfBirth: "2008-03-16",
            placeOfBirth: "Medan",
            email: "nadila.adja@mail.com",
            phone: "+628111111115",
            parentName: "Sarah Adja",
            address: "Medan, Indonesia",
            parentFirstName: "Sarah",
            parentLastName: "Adja",
            parentEmail: "sarah.adja@mail.com",
            parentPhone: "+628100000005",
            parentAddress: "Medan, Indonesia",
            payment: "cash",
        },
        {
            id: 6,
            studentId: "STU006",
            photo: "https://randomuser.me/api/portraits/men/6.jpg",
            firstName: "David",
            lastName: "Miller",
            grade: "VIII C",
            dateOfBirth: "2009-11-05",
            placeOfBirth: "Semarang",
            email: "david.miller@mail.com",
            phone: "+628111111116",
            parentName: "James Miller",
            address: "Semarang, Indonesia",
            parentFirstName: "James",
            parentLastName: "Miller",
            parentEmail: "james.miller@mail.com",
            parentPhone: "+628100000006",
            parentAddress: "Semarang, Indonesia",
            payment: "debit",
        },
        {
            id: 7,
            studentId: "STU007",
            photo: "https://randomuser.me/api/portraits/women/7.jpg",
            firstName: "Sophia",
            lastName: "Brown",
            grade: "IX A",
            dateOfBirth: "2007-08-22",
            placeOfBirth: "Bali",
            email: "sophia.brown@mail.com",
            phone: "+628111111117",
            parentName: "Anna Brown",
            address: "Denpasar, Indonesia",
            parentFirstName: "Anna",
            parentLastName: "Brown",
            parentEmail: "anna.brown@mail.com",
            parentPhone: "+628100000007",
            parentAddress: "Denpasar, Indonesia",
            payment: "cash",
        },
        {
            id: 8,
            studentId: "STU008",
            photo: "https://randomuser.me/api/portraits/men/8.jpg",
            firstName: "James",
            lastName: "Wilson",
            grade: "IX B",
            dateOfBirth: "2008-02-11",
            placeOfBirth: "Makassar",
            email: "james.wilson@mail.com",
            phone: "+628111111118",
            parentName: "Andrew Wilson",
            address: "Makassar, Indonesia",
            parentFirstName: "Andrew",
            parentLastName: "Wilson",
            parentEmail: "andrew.wilson@mail.com",
            parentPhone: "+628100000008",
            parentAddress: "Makassar, Indonesia",
            payment: "debit",
        },
        {
            id: 9,
            studentId: "STU009",
            photo: "https://randomuser.me/api/portraits/women/9.jpg",
            firstName: "Olivia",
            lastName: "Taylor",
            grade: "IX C",
            dateOfBirth: "2007-12-28",
            placeOfBirth: "Palembang",
            email: "olivia.taylor@mail.com",
            phone: "+628111111119",
            parentName: "Emma Taylor",
            address: "Palembang, Indonesia",
            parentFirstName: "Emma",
            parentLastName: "Taylor",
            parentEmail: "emma.taylor@mail.com",
            parentPhone: "+628100000009",
            parentAddress: "Palembang, Indonesia",
            payment: "cash",
        },
        {
            id: 10,
            studentId: "STU010",
            photo: "https://randomuser.me/api/portraits/men/10.jpg",
            firstName: "Daniel",
            lastName: "Scott",
            grade: "X A",
            dateOfBirth: "2008-10-14",
            placeOfBirth: "Bogor",
            email: "daniel.scott@mail.com",
            phone: "+628111111120",
            parentName: "Peter Scott",
            address: "Bogor, Indonesia",
            parentFirstName: "Peter",
            parentLastName: "Scott",
            parentEmail: "peter.scott@mail.com",
            parentPhone: "+628100000010",
            parentAddress: "Bogor, Indonesia",
            payment: "debit",
        }, {
            id: 11,
            studentId: "STU011",
            photo: "https://randomuser.me/api/portraits/women/11.jpg",
            firstName: "Emma",
            lastName: "Watson",
            grade: "X B",
            dateOfBirth: "2007-09-18",
            placeOfBirth: "Jakarta",
            email: "emma.watson@mail.com",
            phone: "+628111111121",
            parentName: "Olivia Watson",
            address: "Jakarta, Indonesia",
            parentFirstName: "Olivia",
            parentLastName: "Watson",
            parentEmail: "olivia.watson@mail.com",
            parentPhone: "+628100000011",
            parentAddress: "Jakarta, Indonesia",
            payment: "cash",
        },
        {
            id: 12,
            studentId: "STU012",
            photo: "https://randomuser.me/api/portraits/men/12.jpg",
            firstName: "Ryan",
            lastName: "Cooper",
            grade: "X C",
            dateOfBirth: "2008-04-25",
            placeOfBirth: "Bandung",
            email: "ryan.cooper@mail.com",
            phone: "+628111111122",
            parentName: "Daniel Cooper",
            address: "Bandung, Indonesia",
            parentFirstName: "Daniel",
            parentLastName: "Cooper",
            parentEmail: "daniel.cooper@mail.com",
            parentPhone: "+628100000012",
            parentAddress: "Bandung, Indonesia",
            payment: "debit",
        },
        {
            id: 13,
            studentId: "STU013",
            photo: "https://randomuser.me/api/portraits/women/13.jpg",
            firstName: "Charlotte",
            lastName: "Hall",
            grade: "XI A",
            dateOfBirth: "2007-06-11",
            placeOfBirth: "Surabaya",
            email: "charlotte.hall@mail.com",
            phone: "+628111111123",
            parentName: "Sophia Hall",
            address: "Surabaya, Indonesia",
            parentFirstName: "Sophia",
            parentLastName: "Hall",
            parentEmail: "sophia.hall@mail.com",
            parentPhone: "+628100000013",
            parentAddress: "Surabaya, Indonesia",
            payment: "cash",
        },
        {
            id: 14,
            studentId: "STU014",
            photo: "https://randomuser.me/api/portraits/men/14.jpg",
            firstName: "Ethan",
            lastName: "Walker",
            grade: "XI B",
            dateOfBirth: "2008-08-02",
            placeOfBirth: "Medan",
            email: "ethan.walker@mail.com",
            phone: "+628111111124",
            parentName: "George Walker",
            address: "Medan, Indonesia",
            parentFirstName: "George",
            parentLastName: "Walker",
            parentEmail: "george.walker@mail.com",
            parentPhone: "+628100000014",
            parentAddress: "Medan, Indonesia",
            payment: "debit",
        },
        {
            id: 15,
            studentId: "STU015",
            photo: "https://randomuser.me/api/portraits/women/15.jpg",
            firstName: "Mia",
            lastName: "Lewis",
            grade: "XI C",
            dateOfBirth: "2007-01-20",
            placeOfBirth: "Yogyakarta",
            email: "mia.lewis@mail.com",
            phone: "+628111111125",
            parentName: "Grace Lewis",
            address: "Yogyakarta, Indonesia",
            parentFirstName: "Grace",
            parentLastName: "Lewis",
            parentEmail: "grace.lewis@mail.com",
            parentPhone: "+628100000015",
            parentAddress: "Yogyakarta, Indonesia",
            payment: "cash",
        },
        {
            id: 16,
            studentId: "STU016",
            photo: "https://randomuser.me/api/portraits/men/16.jpg",
            firstName: "Noah",
            lastName: "Young",
            grade: "XII A",
            dateOfBirth: "2006-11-09",
            placeOfBirth: "Semarang",
            email: "noah.young@mail.com",
            phone: "+628111111126",
            parentName: "Henry Young",
            address: "Semarang, Indonesia",
            parentFirstName: "Henry",
            parentLastName: "Young",
            parentEmail: "henry.young@mail.com",
            parentPhone: "+628100000016",
            parentAddress: "Semarang, Indonesia",
            payment: "debit",
        },
        {
            id: 17,
            studentId: "STU017",
            photo: "https://randomuser.me/api/portraits/women/17.jpg",
            firstName: "Ava",
            lastName: "Green",
            grade: "XII B",
            dateOfBirth: "2006-07-28",
            placeOfBirth: "Denpasar",
            email: "ava.green@mail.com",
            phone: "+628111111127",
            parentName: "Julia Green",
            address: "Denpasar, Indonesia",
            parentFirstName: "Julia",
            parentLastName: "Green",
            parentEmail: "julia.green@mail.com",
            parentPhone: "+628100000017",
            parentAddress: "Denpasar, Indonesia",
            payment: "cash",
        },
        {
            id: 18,
            studentId: "STU018",
            photo: "https://randomuser.me/api/portraits/men/18.jpg",
            firstName: "Lucas",
            lastName: "King",
            grade: "XII C",
            dateOfBirth: "2006-05-15",
            placeOfBirth: "Makassar",
            email: "lucas.king@mail.com",
            phone: "+628111111128",
            parentName: "Thomas King",
            address: "Makassar, Indonesia",
            parentFirstName: "Thomas",
            parentLastName: "King",
            parentEmail: "thomas.king@mail.com",
            parentPhone: "+628100000018",
            parentAddress: "Makassar, Indonesia",
            payment: "debit",
        },
        {
            id: 19,
            studentId: "STU019",
            photo: "https://randomuser.me/api/portraits/women/19.jpg",
            firstName: "Lily",
            lastName: "Adams",
            grade: "VII D",
            dateOfBirth: "2009-02-14",
            placeOfBirth: "Palembang",
            email: "lily.adams@mail.com",
            phone: "+628111111129",
            parentName: "Rachel Adams",
            address: "Palembang, Indonesia",
            parentFirstName: "Rachel",
            parentLastName: "Adams",
            parentEmail: "rachel.adams@mail.com",
            parentPhone: "+628100000019",
            parentAddress: "Palembang, Indonesia",
            payment: "cash",
        },
        {
            id: 20,
            studentId: "STU020",
            photo: "https://randomuser.me/api/portraits/men/20.jpg",
            firstName: "Benjamin",
            lastName: "White",
            grade: "IX D",
            dateOfBirth: "2008-12-03",
            placeOfBirth: "Bogor",
            email: "benjamin.white@mail.com",
            phone: "+628111111130",
            parentName: "Richard White",
            address: "Bogor, Indonesia",
            parentFirstName: "Richard",
            parentLastName: "White",
            parentEmail: "richard.white@mail.com",
            parentPhone: "+628100000020",
            parentAddress: "Bogor, Indonesia",
            payment: "debit",
        },],
    },
    reducers: {
        addStudent: (state, action) => {
            state.students.push({
                id: Date.now(),
                studentId: `STU${String(state.students.length + 1).padStart(3, "0")}`,
                grade: "X B",
                ...action.payload,
            })
        },
        removeStudent: (state, action) => {
            state.students = state.students.filter(
                (student) => student.id !== action.payload
            )
        }, 
        editStudent: (state, action) => {
            const index = state.students.findIndex(
                (student) => student.id === action.payload.id
            )
            if (index !== -1) {
                state.students[index] = action.payload
            }
        }
    },
})

export const {
    addStudent,
    removeStudent,
    editStudent,
} = StudentSlice.actions

export default StudentSlice.reducer