import { createSlice } from "@reduxjs/toolkit";

export const TeacherSlice = createSlice({
    name: "teacher",
    initialState: {
        teachers: [
            {
                id: 1,
                firstName: "Maria",
                lastName: "Historia",
                email: "maria.historia@gmail.com",
                phone: "+628111111111",
                address: "Jakarta, Indonesia",
                photo: "https://i.pravatar.cc/150?img=41",
                dateOfBirth: "1990-02-14",
                placeOfBirth: "Jakarta",
                university: "University Academy Historia",
                degree: "History Major",
                startDate: "2010-09-01",
                endDate: "2014-06-01",
                city: "Jakarta",
            },
            {
                id: 2,
                firstName: "Tony",
                lastName: "Soap",
                email: "tony.soap@gmail.com",
                phone: "+628111111112",
                address: "Bandung, Indonesia",
                photo: "https://i.pravatar.cc/150?img=42",
                dateOfBirth: "1989-08-10",
                placeOfBirth: "Bandung",
                university: "Bandung State University",
                degree: "Mathematics",
                startDate: "2008-09-01",
                endDate: "2012-06-01",
                city: "Bandung",
            },
            {
                id: 3,
                firstName: "Karen",
                lastName: "Hope",
                email: "karen.hope@gmail.com",
                phone: "+628111111113",
                address: "Surabaya, Indonesia",
                photo: "https://i.pravatar.cc/150?img=43",
                dateOfBirth: "1991-04-22",
                placeOfBirth: "Surabaya",
                university: "Surabaya University",
                degree: "English Literature",
                startDate: "2009-09-01",
                endDate: "2013-06-01",
                city: "Surabaya",
            },
            {
                id: 4,
                firstName: "John",
                lastName: "Smith",
                email: "john.smith@gmail.com",
                phone: "+628111111114",
                address: "Yogyakarta, Indonesia",
                photo: "https://i.pravatar.cc/150?img=44",
                dateOfBirth: "1988-12-18",
                placeOfBirth: "Yogyakarta",
                university: "UGM",
                degree: "Physics",
                startDate: "2007-09-01",
                endDate: "2011-06-01",
                city: "Yogyakarta",
            },
            {
                id: 5,
                firstName: "Emma",
                lastName: "Watson",
                email: "emma.watson@gmail.com",
                phone: "+628111111115",
                address: "Bali, Indonesia",
                photo: "https://i.pravatar.cc/150?img=45",
                dateOfBirth: "1993-07-08",
                placeOfBirth: "Denpasar",
                university: "Bali State University",
                degree: "Biology",
                startDate: "2011-09-01",
                endDate: "2015-06-01",
                city: "Denpasar",
            },
            {
                id: 6,
                firstName: "David",
                lastName: "Miller",
                email: "david.miller@gmail.com",
                phone: "+628111111116",
                address: "Medan, Indonesia",
                photo: "https://i.pravatar.cc/150?img=46",
                dateOfBirth: "1992-01-11",
                placeOfBirth: "Medan",
                university: "North Sumatra University",
                degree: "Computer Science",
                startDate: "2010-09-01",
                endDate: "2014-06-01",
                city: "Medan",
            },
            {
                id: 7,
                firstName: "Sophia",
                lastName: "Brown",
                email: "sophia.brown@gmail.com",
                phone: "+628111111117",
                address: "Makassar, Indonesia",
                photo: "https://i.pravatar.cc/150?img=47",
                dateOfBirth: "1990-09-16",
                placeOfBirth: "Makassar",
                university: "Hasanuddin University",
                degree: "Chemistry",
                startDate: "2008-09-01",
                endDate: "2012-06-01",
                city: "Makassar",
            },
            {
                id: 8,
                firstName: "James",
                lastName: "Wilson",
                email: "james.wilson@gmail.com",
                phone: "+628111111118",
                address: "Semarang, Indonesia",
                photo: "https://i.pravatar.cc/150?img=48",
                dateOfBirth: "1987-03-19",
                placeOfBirth: "Semarang",
                university: "Diponegoro University",
                degree: "Economics",
                startDate: "2006-09-01",
                endDate: "2010-06-01",
                city: "Semarang",
            },
            {
                id: 9,
                firstName: "Olivia",
                lastName: "Taylor",
                email: "olivia.taylor@gmail.com",
                phone: "+628111111119",
                address: "Bogor, Indonesia",
                photo: "https://i.pravatar.cc/150?img=49",
                dateOfBirth: "1991-10-27",
                placeOfBirth: "Bogor",
                university: "Bogor Agricultural University",
                degree: "Agriculture",
                startDate: "2009-09-01",
                endDate: "2013-06-01",
                city: "Bogor",
            },
            {
                id: 10,
                firstName: "Daniel",
                lastName: "Scott",
                email: "daniel.scott@gmail.com",
                phone: "+628111111120",
                address: "Malang, Indonesia",
                photo: "https://i.pravatar.cc/150?img=50",
                dateOfBirth: "1992-06-15",
                placeOfBirth: "Malang",
                university: "Brawijaya University",
                degree: "Mechanical Engineering",
                startDate: "2010-09-01",
                endDate: "2014-06-01",
                city: "Malang",
            },
            {
                id: 11,
                firstName: "Linda",
                lastName: "Johnson",
                email: "linda.johnson@gmail.com",
                phone: "+628111111121",
                address: "Bekasi, Indonesia",
                photo: "https://i.pravatar.cc/150?img=51",
                dateOfBirth: "1989-11-05",
                placeOfBirth: "Bekasi",
                university: "Indonesia University",
                degree: "Accounting",
                startDate: "2007-09-01",
                endDate: "2011-06-01",
                city: "Bekasi",
            },
            {
                id: 12,
                firstName: "Andrew",
                lastName: "Thomas",
                email: "andrew.thomas@gmail.com",
                phone: "+628111111122",
                address: "Solo, Indonesia",
                photo: "https://i.pravatar.cc/150?img=52",
                dateOfBirth: "1993-01-29",
                placeOfBirth: "Solo",
                university: "Sebelas Maret University",
                degree: "Law",
                startDate: "2011-09-01",
                endDate: "2015-06-01",
                city: "Solo",
            },
            {
                id: 13,
                firstName: "Grace",
                lastName: "Lee",
                email: "grace.lee@gmail.com",
                phone: "+628111111123",
                address: "Depok, Indonesia",
                photo: "https://i.pravatar.cc/150?img=53",
                dateOfBirth: "1990-04-07",
                placeOfBirth: "Depok",
                university: "Indonesia University",
                degree: "Psychology",
                startDate: "2008-09-01",
                endDate: "2012-06-01",
                city: "Depok",
            },
            {
                id: 14,
                firstName: "Michael",
                lastName: "Clark",
                email: "michael.clark@gmail.com",
                phone: "+628111111124",
                address: "Palembang, Indonesia",
                photo: "https://i.pravatar.cc/150?img=54",
                dateOfBirth: "1988-08-20",
                placeOfBirth: "Palembang",
                university: "Sriwijaya University",
                degree: "Geography",
                startDate: "2006-09-01",
                endDate: "2010-06-01",
                city: "Palembang",
            },
            {
                id: 15,
                firstName: "Natalie",
                lastName: "White",
                email: "natalie.white@gmail.com",
                phone: "+628111111125",
                address: "Batam, Indonesia",
                photo: "https://i.pravatar.cc/150?img=55",
                dateOfBirth: "1992-05-09",
                placeOfBirth: "Batam",
                university: "Batam University",
                degree: "Business Administration",
                startDate: "2010-09-01",
                endDate: "2014-06-01",
                city: "Batam",
            },
            {
                id: 16,
                firstName: "Ryan",
                lastName: "Walker",
                email: "ryan.walker@gmail.com",
                phone: "+628111111126",
                address: "Pontianak, Indonesia",
                photo: "https://i.pravatar.cc/150?img=56",
                dateOfBirth: "1991-12-12",
                placeOfBirth: "Pontianak",
                university: "Tanjungpura University",
                degree: "Statistics",
                startDate: "2009-09-01",
                endDate: "2013-06-01",
                city: "Pontianak",
            },
            {
                id: 17,
                firstName: "Victoria",
                lastName: "King",
                email: "victoria.king@gmail.com",
                phone: "+628111111127",
                address: "Lampung, Indonesia",
                photo: "https://i.pravatar.cc/150?img=57",
                dateOfBirth: "1989-02-25",
                placeOfBirth: "Lampung",
                university: "Lampung University",
                degree: "Education",
                startDate: "2007-09-01",
                endDate: "2011-06-01",
                city: "Lampung",
            },
            {
                id: 18,
                firstName: "Christopher",
                lastName: "Hall",
                email: "christopher.hall@gmail.com",
                phone: "+628111111128",
                address: "Aceh, Indonesia",
                photo: "https://i.pravatar.cc/150?img=58",
                dateOfBirth: "1988-10-04",
                placeOfBirth: "Aceh",
                university: "Syiah Kuala University",
                degree: "Political Science",
                startDate: "2006-09-01",
                endDate: "2010-06-01",
                city: "Aceh",
            },
            {
                id: 19,
                firstName: "Isabella",
                lastName: "Green",
                email: "isabella.green@gmail.com",
                phone: "+628111111129",
                address: "Pekanbaru, Indonesia",
                photo: "https://i.pravatar.cc/150?img=59",
                dateOfBirth: "1994-01-18",
                placeOfBirth: "Pekanbaru",
                university: "Riau University",
                degree: "Information Technology",
                startDate: "2012-09-01",
                endDate: "2016-06-01",
                city: "Pekanbaru",
            },
            {
                id: 20,
                firstName: "William",
                lastName: "Moore",
                email: "william.moore@gmail.com",
                phone: "+628111111130",
                address: "Banjarmasin, Indonesia",
                photo: "https://i.pravatar.cc/150?img=60",
                dateOfBirth: "1990-06-30",
                placeOfBirth: "Banjarmasin",
                university: "Lambung Mangkurat University",
                degree: "Computer Engineering",
                startDate: "2008-09-01",
                endDate: "2012-06-01",
                city: "Banjarmasin",
            }
        ]
    },

    reducers: {
        addTeacher: (state, action) => {
            state.teachers.push({
                id: Date.now(),
                ...action.payload,
            })
        },

        removeTeacher: (state, action) => {
            state.teachers = state.teachers.filter(
                teacher => teacher.id !== action.payload
            )
        },
        editTeacher: (state, action) => {
            const index = state.teachers.findIndex(
                (teacher) => teacher.id === action.payload.id
            )
            if (index !== -1) {
                state.teachers[index] = action.payload
            }
        },
    },
})

export const { addTeacher, removeTeacher,editTeacher } = TeacherSlice.actions;

export default TeacherSlice.reducer;